language: cpp

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx  
  
before_install:
  - brew update
  - brew outdated clang || brew upgrade clang  
  - brew outdated cmake || brew upgrade cmake  
  - brew outdated gcc || brew upgrade gcc 
  
addons:
  apt:
   sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - clang
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make 
  - make check

sudo: required
dist: trusty
