language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install Caskroom/cask/osxfuse --force; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then export CXX="g++-9" CC="gcc-9"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-9" CC="clang-9"; fi

addons:
  apt:
    update: true
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - g++-9
    - clang-9
    - libfuse-dev

before_script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 ..

script: 
  - make -j8
  - make check

sudo: required
dist: bionic
osx_image: xcode11
notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - feature/travis-update