language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install Caskroom/cask/osxfuse git-lfs --force; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then export CXX="g++-9" CC="gcc-9"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-9" CC="clang-9"; fi

addons:
  apt:
    update: true
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test" #Hack for 18.04
    - sourceline: "ppa:llvm-toolchain-bionic-9"
    # - ubuntu-toolchain-r-test
    # - llvm-toolchain-bionic-9
    packages:
    - gcc-9
    - g++-9
    - clang-9
    - libfuse-dev

before_script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 ..

script: 
  - make -j8
  - make check

sudo: required
dist: bionic
osx_image: xcode11
notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - feature/migrate-to-lsf