language: cpp

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx  
  
before_install:
  - brew update
  - brew outdated clang || brew upgrade clang  
  - brew outdated cmake || brew upgrade cmake  
  - brew outdated gcc || brew upgrade gcc 
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  
addons:
  apt:
   sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make 
  - make check

sudo: required

dist: trusty
