language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install Caskroom/cask/osxfuse --force; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then export CXX="g++-8" CC="gcc-8"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export CXX="clang++-7.0" CC="clang-7.0"; fi

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-7.0
    packages:
    - gcc-8
    - g++-8
    - clang-7.0
    - libfuse-dev

before_script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 ..

script: 
  - make -j8
  - make check

sudo: required
dist: xenial
osx_image: xcode10.2
notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master