version: 1.0.{build}
configuration: Release
platform: x64
before_build:
- ps: >-
    git submodule update --init --recursive

    cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 .
build:
  verbosity: minimal
  parallel: true
  -ps: >-
    msbuild StegoDisk.sln /t:StegoDisk:check

notifications:
- provider: Email
  to:
  - qwart279@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

branches:
  only:
    - Windows
