version: 1.0.{build}
configuration: Release
platform: x64
before_build:
- ps: >-
    mkdir build

    cd build

    cmake -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 ..
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - qwart279@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false