version: 1.0.{build}
before_build:
- ps: >-
    git submodule update --init --recursive

    cmake -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 .
build:
  verbosity: minimal
  parallel: true
  project: StegoDisk.sln

notifications:
- provider: Email
  to:
  - qwart279@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

branches:
  only:
    - Windows
